In [1]:
import numpy as np

In [2]:
l=[1,2,3,4,5,6]

In [3]:
np.array(l)

array([1, 2, 3, 4, 5, 6])

In [4]:
l1=[4,5,6,7,"sudh",34.565,True]

In [5]:
a1= np.array(l1)

In [6]:
a2 = np.array([[1,2,3],[4,5,6]])

In [7]:
a3= np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [8]:
a1

array(['4', '5', '6', '7', 'sudh', '34.565', 'True'], dtype='<U32')

In [9]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [11]:
a1.ndim   #ndim show the dimension of array

1

In [12]:
a2.ndim

2

In [13]:
a3.ndim

3

In [14]:
a1.size           #size tell the no of element inthe size

7

In [15]:
a2.size

6

In [16]:
a3.size

9

In [17]:
a1.shape

(7,)

In [18]:
a2.shape   #2 row and 3 column

(2, 3)

In [19]:
a3.shape    #3 row 3 column and 1 such kind of matrix , readout in reverse

(1, 3, 3)

In [20]:
np.random.randint(2,50,(2,3,4))

array([[[ 3, 36, 38, 39],
        [29,  2, 32,  6],
        [30,  4, 46,  4]],

       [[20, 39, 26, 23],
        [38, 24, 13, 48],
        [28, 16, 38, 48]]])

In [21]:
np.random.rand(2,3)

array([[0.96653945, 0.12334425, 0.76140088],
       [0.74271338, 0.65021939, 0.82405861]])

In [22]:
a4= np.random.randn(4,4)

In [23]:
a4

array([[-0.90622682, -1.07049022,  1.84509117,  1.8760726 ],
       [-0.03148339, -0.51817008,  0.45308547, -0.26450342],
       [ 1.03523693,  1.31054759,  0.3325894 , -1.10626269],
       [ 1.06749622, -0.70597005,  1.7158389 ,  0.97261111]])

In [24]:
a4.reshape(8,2)   #always be the factorial of the original data in this case it should be factorial of 16

array([[-0.90622682, -1.07049022],
       [ 1.84509117,  1.8760726 ],
       [-0.03148339, -0.51817008],
       [ 0.45308547, -0.26450342],
       [ 1.03523693,  1.31054759],
       [ 0.3325894 , -1.10626269],
       [ 1.06749622, -0.70597005],
       [ 1.7158389 ,  0.97261111]])

In [25]:
a4.reshape(16,1)

array([[-0.90622682],
       [-1.07049022],
       [ 1.84509117],
       [ 1.8760726 ],
       [-0.03148339],
       [-0.51817008],
       [ 0.45308547],
       [-0.26450342],
       [ 1.03523693],
       [ 1.31054759],
       [ 0.3325894 ],
       [-1.10626269],
       [ 1.06749622],
       [-0.70597005],
       [ 1.7158389 ],
       [ 0.97261111]])

In [26]:
a4.reshape(2,-1)  #numpy will automatically detect the factorial 

array([[-0.90622682, -1.07049022,  1.84509117,  1.8760726 , -0.03148339,
        -0.51817008,  0.45308547, -0.26450342],
       [ 1.03523693,  1.31054759,  0.3325894 , -1.10626269,  1.06749622,
        -0.70597005,  1.7158389 ,  0.97261111]])

In [27]:
a4.reshape(2,2,4)

array([[[-0.90622682, -1.07049022,  1.84509117,  1.8760726 ],
        [-0.03148339, -0.51817008,  0.45308547, -0.26450342]],

       [[ 1.03523693,  1.31054759,  0.3325894 , -1.10626269],
        [ 1.06749622, -0.70597005,  1.7158389 ,  0.97261111]]])

In [28]:
a4.reshape(1,1,1,1,1,1,1,2,2,4)

array([[[[[[[[[[-0.90622682, -1.07049022,  1.84509117,
                 1.8760726 ],
               [-0.03148339, -0.51817008,  0.45308547,
                -0.26450342]],

              [[ 1.03523693,  1.31054759,  0.3325894 ,
                -1.10626269],
               [ 1.06749622, -0.70597005,  1.7158389 ,
                 0.97261111]]]]]]]]]])

In [29]:
a1

array(['4', '5', '6', '7', 'sudh', '34.565', 'True'], dtype='<U32')

In [30]:
a1[0]

'4'

In [31]:
a1[2:6]

array(['6', '7', 'sudh', '34.565'], dtype='<U32')

In [32]:
a1[2:6:2]

array(['6', 'sudh'], dtype='<U32')

In [33]:
a1[::-1]

array(['True', '34.565', 'sudh', '7', '6', '5', '4'], dtype='<U32')

In [34]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
a2[0]

array([1, 2, 3])

In [36]:
a2[:,1:]

array([[2, 3],
       [5, 6]])

In [37]:
a2[:,[1,2]]

array([[2, 3],
       [5, 6]])

In [38]:
a2[[0,1],1:]

array([[2, 3],
       [5, 6]])

In [39]:
a5= np.random.randint(2,90,(6,5))

In [40]:
a5

array([[ 7, 34, 82, 26, 72],
       [46, 68, 23, 78, 43],
       [78, 53,  2,  6, 59],
       [42, 57, 24,  2, 16],
       [15, 14, 61, 59, 12],
       [44, 16,  5, 37, 31]])

In [41]:
a5[a5>40]

array([82, 72, 46, 68, 78, 43, 78, 53, 59, 42, 57, 61, 59, 44])

In [42]:
a5

array([[ 7, 34, 82, 26, 72],
       [46, 68, 23, 78, 43],
       [78, 53,  2,  6, 59],
       [42, 57, 24,  2, 16],
       [15, 14, 61, 59, 12],
       [44, 16,  5, 37, 31]])

In [43]:
a5[0,1]=100

In [44]:
a5

array([[  7, 100,  82,  26,  72],
       [ 46,  68,  23,  78,  43],
       [ 78,  53,   2,   6,  59],
       [ 42,  57,  24,   2,  16],
       [ 15,  14,  61,  59,  12],
       [ 44,  16,   5,  37,  31]])

In [45]:
a6=np.random.randint(0,3,(3,3))

In [46]:
a7=np.random.randint(0,3,(3,3))

In [47]:
a6

array([[2, 1, 2],
       [2, 1, 1],
       [0, 0, 2]])

In [48]:
a7

array([[2, 0, 1],
       [1, 0, 1],
       [1, 0, 2]])

In [49]:
a6*a7

array([[4, 0, 2],
       [2, 0, 1],
       [0, 0, 4]])

In [50]:
a6@a7   #matrix multiplication

array([[7, 0, 7],
       [6, 0, 5],
       [2, 0, 4]])

In [51]:
a6

array([[2, 1, 2],
       [2, 1, 1],
       [0, 0, 2]])

In [52]:
a6+100

array([[102, 101, 102],
       [102, 101, 101],
       [100, 100, 102]])

In [53]:
a6*2

array([[4, 2, 4],
       [4, 2, 2],
       [0, 0, 4]])

In [54]:
a6/0

C:\Users\Shubham\AppData\Local\Temp\ipykernel_11256\1058679823.py:1: RuntimeWarning: divide by zero encountered in true_divide
  a6/0
C:\Users\Shubham\AppData\Local\Temp\ipykernel_11256\1058679823.py:1: RuntimeWarning: invalid value encountered in true_divide
  a6/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [nan, nan, inf]])

In [55]:
a6

array([[2, 1, 2],
       [2, 1, 1],
       [0, 0, 2]])

In [56]:
a6**3

array([[8, 1, 8],
       [8, 1, 1],
       [0, 0, 8]], dtype=int32)

In [57]:
a8=np.zeros((4,4))

In [58]:
a9=np.ones((4,5))

In [59]:
a9+10

array([[11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.]])

In [60]:
a9 + np.array([1,2,3,4,5])

array([[2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.]])

In [61]:
a9

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [62]:
np.array([[1,2,3,4]]).T   #transpose the data

array([[1],
       [2],
       [3],
       [4]])

In [63]:
np.array([[1,2,3,4]])

array([[1, 2, 3, 4]])

In [64]:
np.array([[1,2,3,4]]).T +a9

array([[2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5.]])

In [65]:
a6

array([[2, 1, 2],
       [2, 1, 1],
       [0, 0, 2]])

In [66]:
a6.T

array([[2, 2, 0],
       [1, 1, 0],
       [2, 1, 2]])

In [67]:
a5

array([[  7, 100,  82,  26,  72],
       [ 46,  68,  23,  78,  43],
       [ 78,  53,   2,   6,  59],
       [ 42,  57,  24,   2,  16],
       [ 15,  14,  61,  59,  12],
       [ 44,  16,   5,  37,  31]])

In [68]:
np.sqrt(a5) #squareroot of all the element

array([[ 2.64575131, 10.        ,  9.05538514,  5.09901951,  8.48528137],
       [ 6.78232998,  8.24621125,  4.79583152,  8.83176087,  6.55743852],
       [ 8.83176087,  7.28010989,  1.41421356,  2.44948974,  7.68114575],
       [ 6.4807407 ,  7.54983444,  4.89897949,  1.41421356,  4.        ],
       [ 3.87298335,  3.74165739,  7.81024968,  7.68114575,  3.46410162],
       [ 6.63324958,  4.        ,  2.23606798,  6.08276253,  5.56776436]])

In [69]:
np.log10(a5)

array([[0.84509804, 2.        , 1.91381385, 1.41497335, 1.8573325 ],
       [1.66275783, 1.83250891, 1.36172784, 1.8920946 , 1.63346846],
       [1.8920946 , 1.72427587, 0.30103   , 0.77815125, 1.77085201],
       [1.62324929, 1.75587486, 1.38021124, 0.30103   , 1.20411998],
       [1.17609126, 1.14612804, 1.78532984, 1.77085201, 1.07918125],
       [1.64345268, 1.20411998, 0.69897   , 1.56820172, 1.49136169]])

In [70]:
np.exp(a5)

array([[1.09663316e+03, 2.68811714e+43, 4.09399696e+35, 1.95729609e+11,
        1.85867175e+31],
       [9.49611942e+19, 3.40427605e+29, 9.74480345e+09, 7.49841700e+33,
        4.72783947e+18],
       [7.49841700e+33, 1.04137594e+23, 7.38905610e+00, 4.03428793e+02,
        4.20121040e+25],
       [1.73927494e+18, 5.68572000e+24, 2.64891221e+10, 7.38905610e+00,
        8.88611052e+06],
       [3.26901737e+06, 1.20260428e+06, 3.10429794e+26, 4.20121040e+25,
        1.62754791e+05],
       [1.28516001e+19, 8.88611052e+06, 1.48413159e+02, 1.17191424e+16,
        2.90488497e+13]])

In [71]:
list(range(0,10,2))

[0, 2, 4, 6, 8]

In [72]:
np.arange(1,10,2.5)

array([1. , 3.5, 6. , 8.5])

In [73]:
np.arange(1.8,10.7,2.5)

array([1.8, 4.3, 6.8, 9.3])

In [74]:
np.linspace(2,3,num=50)

array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
       2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
       2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
       2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
       2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
       2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
       2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
       2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
       2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
       2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ])

In [75]:
np.logspace(2,4,num=4,base=10)

array([  100.        ,   464.15888336,  2154.43469003, 10000.        ])

In [76]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [77]:
#data visualization

In [80]:
import cufflinks as cf
import numpy as np
import pandas as pd
import seaborn as sns

In [81]:
!pip install cufflinks

In [82]:
cf.go_offline()

In [86]:
df= pd.DataFrame(np.random.randn(100,3),columns=['A','B','C'])

In [87]:
df

A         B         C
0   0.115761 -0.955946 -0.816210
1  -1.284291  0.431798  0.186992
2   0.200730 -0.599020 -1.286033
3   0.136963 -0.616015  0.796732
4   0.541436  0.406063 -0.560050
..       ...       ...       ...
95  0.967676  1.614719  0.132363
96  0.359820  1.246691  0.187541
97  0.494723  0.359396  0.009020
98  1.546706  0.247419 -0.734107
99 -1.847388  0.249222 -0.276540

[100 rows x 3 columns]

In [93]:
df.iplot()

In [90]:
df1= pd.DataFrame(np.random.randint(3,100,(100,1)))

In [91]:
df1.iplot()

In [92]:
df1

0
0   42
1   53
2   60
3   89
4   36
..  ..
95  48
96  57
97  82
98  76
99  23

[100 rows x 1 columns]

In [94]:
df

A         B         C
0   0.115761 -0.955946 -0.816210
1  -1.284291  0.431798  0.186992
2   0.200730 -0.599020 -1.286033
3   0.136963 -0.616015  0.796732
4   0.541436  0.406063 -0.560050
..       ...       ...       ...
95  0.967676  1.614719  0.132363
96  0.359820  1.246691  0.187541
97  0.494723  0.359396  0.009020
98  1.546706  0.247419 -0.734107
99 -1.847388  0.249222 -0.276540

[100 rows x 3 columns]

In [96]:
df.iplot(x='A',y='B',mode='markers')

In [98]:
df2= sns.load_dataset('titanic')

In [99]:
df2.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [100]:
df2.iplot(x='age',y='fare',mode='markers')

In [101]:
df2.iplot(x='age',y='pclass',mode='markers')

In [102]:
df2.iplot(x='fare',y='pclass',mode='markers')

In [103]:
df2.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [104]:
df2.iplot(kind='bar',x='sex',y='survived')