In [1]:
import pandas as pd

In [2]:
data = {'name' : ['sudh','krish','hitest','tulesko'],
       'salary' : [100,200,300,400],
        'mail_id':['sudh@ineuron.ai','krish@ineuron.ai','hitesh@ineuron.ai','tulesko@ineuron.ai'],
        'addr': ['blr','blr','blr','mum']
}

In [3]:
pd.DataFrame(data)

name  salary             mail_id addr
0     sudh     100     sudh@ineuron.ai  blr
1    krish     200    krish@ineuron.ai  blr
2   hitest     300   hitesh@ineuron.ai  blr
3  tulesko     400  tulesko@ineuron.ai  mum

In [4]:
pd.DataFrame(data , columns=[0,1,2,3])  #it will not return data as the data is in key value pair

Empty DataFrame
Columns: [0, 1, 2, 3]
Index: []

In [5]:
pd.DataFrame(data, index=[4,5,6,7])   #indexing will return data 

name  salary             mail_id addr
4     sudh     100     sudh@ineuron.ai  blr
5    krish     200    krish@ineuron.ai  blr
6   hitest     300   hitesh@ineuron.ai  blr
7  tulesko     400  tulesko@ineuron.ai  mum

In [6]:
df = pd.DataFrame(data, index=[0,1,2,3])

In [7]:
df

name  salary             mail_id addr
0     sudh     100     sudh@ineuron.ai  blr
1    krish     200    krish@ineuron.ai  blr
2   hitest     300   hitesh@ineuron.ai  blr
3  tulesko     400  tulesko@ineuron.ai  mum

In [8]:
df.loc[5:6]   #loc goes for the current indexes present inside the data

Empty DataFrame
Columns: [name, salary, mail_id, addr]
Index: []

In [9]:
df.iloc[1:2]    #iloc goes for default indexes 

name  salary           mail_id addr
1  krish     200  krish@ineuron.ai  blr

In [10]:
df

name  salary             mail_id addr
0     sudh     100     sudh@ineuron.ai  blr
1    krish     200    krish@ineuron.ai  blr
2   hitest     300   hitesh@ineuron.ai  blr
3  tulesko     400  tulesko@ineuron.ai  mum

In [11]:
data1 = {'pf_nu' : [234,45,54465,656],
        'income_tax' : [234,565,767,6778],
        'mobile_no' : [23543,43543,454,5656],
        'courses' : ['ds','bigdata','web dev','blockchain']
        }

In [12]:
df1 = pd.DataFrame(data1)

In [13]:
df1

pf_nu  income_tax  mobile_no     courses
0    234         234      23543          ds
1     45         565      43543     bigdata
2  54465         767        454     web dev
3    656        6778       5656  blockchain

In [14]:
pd.concat([df,df1])    #vertical concatination

name  salary             mail_id addr    pf_nu  income_tax  mobile_no  \
0     sudh   100.0     sudh@ineuron.ai  blr      NaN         NaN        NaN   
1    krish   200.0    krish@ineuron.ai  blr      NaN         NaN        NaN   
2   hitest   300.0   hitesh@ineuron.ai  blr      NaN         NaN        NaN   
3  tulesko   400.0  tulesko@ineuron.ai  mum      NaN         NaN        NaN   
0      NaN     NaN                 NaN  NaN    234.0       234.0    23543.0   
1      NaN     NaN                 NaN  NaN     45.0       565.0    43543.0   
2      NaN     NaN                 NaN  NaN  54465.0       767.0      454.0   
3      NaN     NaN                 NaN  NaN    656.0      6778.0     5656.0   

      courses  
0         NaN  
1         NaN  
2         NaN  
3         NaN  
0          ds  
1     bigdata  
2     web dev  
3  blockchain

In [15]:
pd.concat([df,df1], axis=1)   #horizontal concatination

name  salary             mail_id addr  pf_nu  income_tax  mobile_no  \
0     sudh     100     sudh@ineuron.ai  blr    234         234      23543   
1    krish     200    krish@ineuron.ai  blr     45         565      43543   
2   hitest     300   hitesh@ineuron.ai  blr  54465         767        454   
3  tulesko     400  tulesko@ineuron.ai  mum    656        6778       5656   

      courses  
0          ds  
1     bigdata  
2     web dev  
3  blockchain

In [16]:
data2 = {'0' : ['sudh','krish','hitest','tulesko'],
       '1' : [100,200,300,400],
        '2':['sudh@ineuron.ai','krish@ineuron.ai','hitesh@ineuron.ai','tulesko@ineuron.ai'],
        '3': ['blr','blr','blr','mum']
}

In [17]:
data3 = {'0' : [234,45,54465,656],
        '1' : [234,565,767,6778],
        '2' : [23543,43543,454,5656],
        '3' : ['ds','bigdata','web dev','blockchain']
        }

In [18]:
df2 = pd.DataFrame(data2)

In [19]:
df3 = pd.DataFrame(data3)

In [20]:
pd.concat([df2,df3])

0     1                   2           3
0     sudh   100     sudh@ineuron.ai         blr
1    krish   200    krish@ineuron.ai         blr
2   hitest   300   hitesh@ineuron.ai         blr
3  tulesko   400  tulesko@ineuron.ai         mum
0      234   234               23543          ds
1       45   565               43543     bigdata
2    54465   767                 454     web dev
3      656  6778                5656  blockchain

In [21]:
data4 = {'emp_id' : [101,102,103,104],
         'salary' : [234,345,200,400],
         'pf' : [23,34,56,78],
}

In [22]:
data5 = {'emp_id': [101,102,104,105],
         'mob_no': [3434,5656,767,878],
         'house_nu' : [345,345,345,56]
}

In [23]:
df4 = pd.DataFrame(data4)

In [24]:
df4

emp_id  salary  pf
0     101     234  23
1     102     345  34
2     103     200  56
3     104     400  78

In [25]:
df5 = pd.DataFrame(data5)

In [26]:
df5

emp_id  mob_no  house_nu
0     101    3434       345
1     102    5656       345
2     104     767       345
3     105     878        56

In [27]:
pd.merge(df4,df5)     #common values will be merged

emp_id  salary  pf  mob_no  house_nu
0     101     234  23    3434       345
1     102     345  34    5656       345
2     104     400  78     767       345

In [80]:
pd.merge(df4,df5 , how='left')     #merging will be done by the values according to df in the left in this case df4

emp_id  salary  pf  mob_no  house_nu
0     101     234  23  3434.0     345.0
1     102     345  34  5656.0     345.0
2     103     200  56     NaN       NaN
3     104     400  78   767.0     345.0

In [81]:
pd.merge(df4,df5 , how='right')   #merging will be done by the values according to df in the right in this case df5

emp_id  salary    pf  mob_no  house_nu
0     101   234.0  23.0    3434       345
1     102   345.0  34.0    5656       345
2     104   400.0  78.0     767       345
3     105     NaN   NaN     878        56

In [29]:
pd.merge(df4,df5 , how='right', on = 'emp_id')

emp_id  salary    pf  mob_no  house_nu
0     101   234.0  23.0    3434       345
1     102   345.0  34.0    5656       345
2     104   400.0  78.0     767       345
3     105     NaN   NaN     878        56

In [30]:
data6 = {'emp_id1' : [101,102,103,104],
         'salary' : [234,345,200,400],
         'pf' : [23,34,56,78],
}

data7 = {'emp_id2': [101,102,104,105],
         'mob_no': [3434,5656,767,878],
         'house_nu' : [345,345,345,56]
}

In [31]:
df6 = pd.DataFrame(data6)

In [32]:
df7 = pd.DataFrame(data7)

In [33]:
df6

emp_id1  salary  pf
0      101     234  23
1      102     345  34
2      103     200  56
3      104     400  78

In [34]:
df7

emp_id2  mob_no  house_nu
0      101    3434       345
1      102    5656       345
2      104     767       345
3      105     878        56

In [35]:
pd.merge(df6,df7 , left_on = 'emp_id1' , right_on = 'emp_id2' , how = 'inner')

emp_id1  salary  pf  emp_id2  mob_no  house_nu
0      101     234  23      101    3434       345
1      102     345  34      102    5656       345
2      104     400  78      104     767       345

In [36]:
data8 = {'emp_id' : [101,102,103,104],
         'salary' : [234,345,200,400],
         'pf' : [23,34,56,78],
}

data9 = {'emp_id': [101,102,104,105],
         'salary': [234,345,200,878],
         'house_nu' : [345,345,345,56]
}

In [37]:
df8 = pd.DataFrame(data8)

In [38]:
df9 = pd.DataFrame(data9)

In [39]:
df8

emp_id  salary  pf
0     101     234  23
1     102     345  34
2     103     200  56
3     104     400  78

In [40]:
df9

emp_id  salary  house_nu
0     101     234       345
1     102     345       345
2     104     200       345
3     105     878        56

In [41]:
pd.merge(df8,df9 , on = ['emp_id','salary'])   #check the common dataset berfore merging

emp_id  salary  pf  house_nu
0     101     234  23       345
1     102     345  34       345

In [42]:
data10 = {'emp_id1' : [101,102,103,104],
         'salary1' : [234,345,200,400],
         'pf' : [23,34,56,78],
}

data11 = {'emp_id2': [101,102,104,105,123],
         'salary2': [234,345,200,878,43],
         'house_nu' : [345,345,345,56,234]
}

In [43]:
df10 = pd.DataFrame(data10,index = ['a','b','c','d'])

In [44]:
df11 = pd.DataFrame(data11 , index = ['a','b','d','e','f'])

In [45]:
df10

emp_id1  salary1  pf
a      101      234  23
b      102      345  34
c      103      200  56
d      104      400  78

In [46]:
df11

emp_id2  salary2  house_nu
a      101      234       345
b      102      345       345
d      104      200       345
e      105      878        56
f      123       43       234

In [47]:
df10.join(df11)   #column match operation and giving outcome of joining

emp_id1  salary1  pf  emp_id2  salary2  house_nu
a      101      234  23    101.0    234.0     345.0
b      102      345  34    102.0    345.0     345.0
c      103      200  56      NaN      NaN       NaN
d      104      400  78    104.0    200.0     345.0

In [48]:
df10.join(df11 , how = 'left')

emp_id1  salary1  pf  emp_id2  salary2  house_nu
a      101      234  23    101.0    234.0     345.0
b      102      345  34    102.0    345.0     345.0
c      103      200  56      NaN      NaN       NaN
d      104      400  78    104.0    200.0     345.0

In [49]:
df10.join(df11 , how = 'right')

emp_id1  salary1    pf  emp_id2  salary2  house_nu
a    101.0    234.0  23.0      101      234       345
b    102.0    345.0  34.0      102      345       345
d    104.0    400.0  78.0      104      200       345
e      NaN      NaN   NaN      105      878        56
f      NaN      NaN   NaN      123       43       234

In [50]:
df_sales = pd.read_csv('E:\data science\pandas\pandas class 2\sales_data_final.csv')

In [51]:
df_sales.head()

order_id order_date ship_date       ship_mode    customer_name  \
0     AG-2011-2040   1/1/2011  1/6/2011  Standard Class  Toby Braunhardt   
1    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   
2     HU-2011-1220   1/1/2011  1/5/2011    Second Class    Annie Thurman   
3  IT-2011-3647632   1/1/2011  1/5/2011    Second Class     Eugene Moren   
4    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   

       segment            state    country  market   region  ...  \
0     Consumer      Constantine    Algeria  Africa   Africa  ...   
1     Consumer  New South Wales  Australia    APAC  Oceania  ...   
2     Consumer         Budapest    Hungary    EMEA     EMEA  ...   
3  Home Office        Stockholm     Sweden      EU    North  ...   
4     Consumer  New South Wales  Australia    APAC  Oceania  ...   

          category sub_category                 product_name sales quantity  \
0  Office Supplies      Storage          Tenex Lockers, Blue   408        2   
1  Office Supplies     Supplies     Acme Trimmer, High Speed   120        3   
2  Office Supplies      Storage      Tenex Box, Single Width    66        4   
3  Office Supplies        Paper  Enermax Note Cards, Premium    45        3   
4        Furniture  Furnishings   Eldon Light Bulb, Duo Pack   114        5   

   discount   profit  shipping_cost  order_priority  year  
0       0.0  106.140          35.46          Medium  2011  
1       0.1   36.036           9.72          Medium  2011  
2       0.0   29.640           8.17            High  2011  
3       0.5  -26.055           4.82            High  2011  
4       0.1   37.770           4.70          Medium  2011  

[5 rows x 21 columns]

In [52]:
def profit_flag(a):
    if a > 0:
        return 'positive'
    else:
        return 'negative'

In [53]:
profit_flag(-45)

'negative'

In [54]:
profit_flag(33)

'positive'

In [55]:
df_sales['flag_profit']=df_sales['profit'].apply(profit_flag)

In [56]:
df_sales.head()

order_id order_date ship_date       ship_mode    customer_name  \
0     AG-2011-2040   1/1/2011  1/6/2011  Standard Class  Toby Braunhardt   
1    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   
2     HU-2011-1220   1/1/2011  1/5/2011    Second Class    Annie Thurman   
3  IT-2011-3647632   1/1/2011  1/5/2011    Second Class     Eugene Moren   
4    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   

       segment            state    country  market   region  ... sub_category  \
0     Consumer      Constantine    Algeria  Africa   Africa  ...      Storage   
1     Consumer  New South Wales  Australia    APAC  Oceania  ...     Supplies   
2     Consumer         Budapest    Hungary    EMEA     EMEA  ...      Storage   
3  Home Office        Stockholm     Sweden      EU    North  ...        Paper   
4     Consumer  New South Wales  Australia    APAC  Oceania  ...  Furnishings   

                  product_name sales quantity discount   profit  \
0          Tenex Lockers, Blue   408        2      0.0  106.140   
1     Acme Trimmer, High Speed   120        3      0.1   36.036   
2      Tenex Box, Single Width    66        4      0.0   29.640   
3  Enermax Note Cards, Premium    45        3      0.5  -26.055   
4   Eldon Light Bulb, Duo Pack   114        5      0.1   37.770   

   shipping_cost  order_priority  year flag_profit  
0          35.46          Medium  2011    positive  
1           9.72          Medium  2011    positive  
2           8.17            High  2011    positive  
3           4.82            High  2011    negative  
4           4.70          Medium  2011    positive  

[5 rows x 22 columns]

In [57]:
df_sales['len_cus_name']= df_sales['customer_name'].apply(len)

In [58]:
df_sales.head()

order_id order_date ship_date       ship_mode    customer_name  \
0     AG-2011-2040   1/1/2011  1/6/2011  Standard Class  Toby Braunhardt   
1    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   
2     HU-2011-1220   1/1/2011  1/5/2011    Second Class    Annie Thurman   
3  IT-2011-3647632   1/1/2011  1/5/2011    Second Class     Eugene Moren   
4    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   

       segment            state    country  market   region  ...  \
0     Consumer      Constantine    Algeria  Africa   Africa  ...   
1     Consumer  New South Wales  Australia    APAC  Oceania  ...   
2     Consumer         Budapest    Hungary    EMEA     EMEA  ...   
3  Home Office        Stockholm     Sweden      EU    North  ...   
4     Consumer  New South Wales  Australia    APAC  Oceania  ...   

                  product_name sales quantity discount   profit  \
0          Tenex Lockers, Blue   408        2      0.0  106.140   
1     Acme Trimmer, High Speed   120        3      0.1   36.036   
2      Tenex Box, Single Width    66        4      0.0   29.640   
3  Enermax Note Cards, Premium    45        3      0.5  -26.055   
4   Eldon Light Bulb, Duo Pack   114        5      0.1   37.770   

   shipping_cost  order_priority  year  flag_profit len_cus_name  
0          35.46          Medium  2011     positive           15  
1           9.72          Medium  2011     positive           11  
2           8.17            High  2011     positive           13  
3           4.82            High  2011     negative           12  
4           4.70          Medium  2011     positive           11  

[5 rows x 23 columns]

In [59]:
def quantity_flag(a):
    if a < 10:
        return 'low'
    elif a >10 and a<20:
        return 'medium'
    else :
        return 'high'

In [60]:
df_sales['flag_quantity'] = df_sales['quantity'].apply(quantity_flag)

In [61]:
df_sales.head()

order_id order_date ship_date       ship_mode    customer_name  \
0     AG-2011-2040   1/1/2011  1/6/2011  Standard Class  Toby Braunhardt   
1    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   
2     HU-2011-1220   1/1/2011  1/5/2011    Second Class    Annie Thurman   
3  IT-2011-3647632   1/1/2011  1/5/2011    Second Class     Eugene Moren   
4    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   

       segment            state    country  market   region  ... sales  \
0     Consumer      Constantine    Algeria  Africa   Africa  ...   408   
1     Consumer  New South Wales  Australia    APAC  Oceania  ...   120   
2     Consumer         Budapest    Hungary    EMEA     EMEA  ...    66   
3  Home Office        Stockholm     Sweden      EU    North  ...    45   
4     Consumer  New South Wales  Australia    APAC  Oceania  ...   114   

  quantity discount   profit shipping_cost  order_priority  year  flag_profit  \
0        2      0.0  106.140         35.46          Medium  2011     positive   
1        3      0.1   36.036          9.72          Medium  2011     positive   
2        4      0.0   29.640          8.17            High  2011     positive   
3        3      0.5  -26.055          4.82            High  2011     negative   
4        5      0.1   37.770          4.70          Medium  2011     positive   

   len_cus_name flag_quantity  
0            15           low  
1            11           low  
2            13           low  
3            12           low  
4            11           low  

[5 rows x 24 columns]

In [62]:
df_sales['square_quantity'] =  df_sales['quantity'].apply(lambda a : a**2)

In [63]:
df_sales.head()

order_id order_date ship_date       ship_mode    customer_name  \
0     AG-2011-2040   1/1/2011  1/6/2011  Standard Class  Toby Braunhardt   
1    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   
2     HU-2011-1220   1/1/2011  1/5/2011    Second Class    Annie Thurman   
3  IT-2011-3647632   1/1/2011  1/5/2011    Second Class     Eugene Moren   
4    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   

       segment            state    country  market   region  ... quantity  \
0     Consumer      Constantine    Algeria  Africa   Africa  ...        2   
1     Consumer  New South Wales  Australia    APAC  Oceania  ...        3   
2     Consumer         Budapest    Hungary    EMEA     EMEA  ...        4   
3  Home Office        Stockholm     Sweden      EU    North  ...        3   
4     Consumer  New South Wales  Australia    APAC  Oceania  ...        5   

  discount   profit shipping_cost order_priority  year  flag_profit  \
0      0.0  106.140         35.46         Medium  2011     positive   
1      0.1   36.036          9.72         Medium  2011     positive   
2      0.0   29.640          8.17           High  2011     positive   
3      0.5  -26.055          4.82           High  2011     negative   
4      0.1   37.770          4.70         Medium  2011     positive   

   len_cus_name  flag_quantity square_quantity  
0            15            low               4  
1            11            low               9  
2            13            low              16  
3            12            low               9  
4            11            low              25  

[5 rows x 25 columns]

In [64]:
#numbpy - numerical python

In [65]:
import numpy as np

In [66]:
np.array([2,3,4,5,6])

array([2, 3, 4, 5, 6])

In [67]:
type(np.array([2,3,4,5,6]))

numpy.ndarray

In [68]:
np.array([[2,3,4] , [4,5,6]])

array([[2, 3, 4],
       [4, 5, 6]])

In [69]:
np.array([[1,2,3,4] , [2,3,4,5]])

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [70]:
l = [[1,2,3,4] , [2,3,4,5]]

In [71]:
l[0][0]

1

In [72]:
a = np.array([3,4,5,6] , ndmin=3)

In [73]:
a

array([[[3, 4, 5, 6]]])

In [74]:
arr = np.array([[1,2,3] , [4,5,6] , [7,8,9]])

In [75]:
arr


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [76]:
arr.ndim

2

In [77]:
np.random.randint(1,10,(4,4))

array([[2, 4, 4, 2],
       [3, 4, 9, 2],
       [5, 7, 2, 1],
       [9, 4, 4, 4]])

In [78]:
np.random.randint(1,10,(4,4,2))

array([[[3, 8],
        [8, 2],
        [5, 7],
        [2, 1]],

       [[2, 4],
        [7, 3],
        [1, 3],
        [1, 1]],

       [[9, 1],
        [9, 7],
        [8, 1],
        [6, 1]],

       [[6, 6],
        [1, 2],
        [1, 1],
        [5, 8]]])

In [79]:
#Task 1 - Fitbit Dataset

1. Read this dataset in pandas , mysql and mongodb 
2. while creting a table in mysql dont use manual approach to create it  ,always use a automation to create a table in mysql
 ## hint - use csvkit library to automate this task and to load a data in bulk in you mysql 
3. convert all the dates avaible in dataset to timestamp format in pandas and in sql you to convert it in date format
4 . Find out in this data that how many unique id's we have 
5 . which id is one of the active id that you have in whole dataset 
6 . how many of them have not logged there activity find out in terms of number of ids 
7 . Find out who is the laziest person id that we have in dataset 
8 . Explore over an internet that how much calories burn is required for a healthy person and find out how many healthy person we have in our dataset 
9. how many person are not a regular person with respect to activity try to find out those 
10 . who is the thired most active person in this dataset find out those in pandas and in sql both . 
11 . who is the 5th most laziest person avilable in dataset find it out 
12 . what is a totla acumulative calories burn for a person find out 

SyntaxError: invalid syntax (609992388.py, line 3)

In [ ]:
#task 2 - Superstore_USA
1 . load this data in sql and in pandas with a relation in sql 
2 . while loading this data you dont have to create a table manually you can use any automated approach to create a table and load a data in bulk in table 
3 . Find out how return that we ahve recived and with a product id 
4 . try  to join order and return data both in sql and pandas 
5 . Try to find out how many unique customer that we have 
6 . try to find out in how many regions we are selling a product and who is a manager for a respective region 
7 . find out how many different differnet shipement mode that we have and what is a percentage usablity of all the shipment mode with respect to dataset 
8 . Create a new coulmn and try to find our a diffrence between order date and shipment date
9 . base on question number 8 find out for which order id we have shipment duration more than 10 days 
10 . Try to find out a list of a returned order which sihpment duration was more then 15 days and find out that region manager as well 
11 . Gorup by region and find out which region is more profitable 
12 . Try to find out overalll in which country we are giving more didscount 
13 . Give me a list of unique postal code 
14 . which customer segement is more profitalble find it out . 
15 . try to find out the 10th most loss making product catagory . 
16 . Try to find out 10 top  product with highest margins 
